### PR TITLE
Feature/mysql fixing plugin

### LINKED ISSUE #16: Add MySQL Fixing Plugin
Remove users from a database

### PR DESCRIPTION
**Pull request by ghareeb-falazi**
closes #16
builds on #14

### CODE REVIEW

File: src/main/java/org/iac2/api/controller/PluginController.java [hunk 1]
```diff
@@ -195,8 +191,9 @@ public ResponseEntity<PluginPojo> getPlugin(@PathVariable String id) {
 
     private ComplianceRule getComplianceRule(Long id) {
         ComplianceRuleEntity crEntity = this.complianceRuleRepository.findById(id).orElseThrow();
+        ComplianceRuleConfigurationEntity dummy = new ComplianceRuleConfigurationEntity(crEntity, null, "");
 
-        return EntityToPojo.transformComplianceRule(crEntity, new ArrayList<>());
+        return EntityToPojo.transformComplianceRule(dummy);
```
Comment (nyuuyn) [inline src/main/java/org/iac2/api/controller/PluginController.java:196]: dummy? any bigger meaning behind it? :D

File: src/main/java/org/iac2/common/utility/Edmm.java [hunk 2]
```diff
@@ -263,11 +271,18 @@ public static String findHostIp(RootComponent component, DeploymentModel deploym
...
         String propertyName = attribute.getName();
-        String edmmType = switch (attribute.getType().getName()) {
-            case "java.lang.Integer", "java.lang.Long" -> DefaultKeys.INTEGER;
-            case "java.lang.Float", "java.lang.Double" -> DefaultKeys.FLOAT;
-            default -> DefaultKeys.STRING;
-        };
+        String edmmType = DefaultKeys.STRING;
+        Class<?> javaType = attribute.getType();
+
+        if (Integer.class.equals(javaType) || Long.class.equals(javaType)) {
```
Comment (nyuuyn) [inline src/main/java/org/iac2/common/utility/Edmm.java:277]: maybe some instanceof would be "more straightforward" but you get a Class<?> anyway

File: src/main/java/org/iac2/service/checking/plugin/implementation/subgraphmatching/comparison/ComponentComparisonResult.java [hunk 3]
```diff
@@ -0,0 +1,4 @@
+package org.iac2.service.checking.plugin.implementation.subgraphmatching.comparison;
+
+public record ComponentComparisonResult(ComponentComparisonOutcome outcome, String propertyName, String expression) {
```
Comment (nyuuyn) [inline src/main/java/org/iac2/service/checking/plugin/implementation/subgraphmatching/comparison/ComponentComparisonResult.java:3]: record? what?

https://www.geeksforgeeks.org/what-are-java-records-and-how-to-use-them-alongside-constructors-and-methods/ 
I'm getting old <.<

**Review by nyuuyn — APPROVED** [review]
LGTM

File: src/main/java/org/iac2/common/utility/Edmm.java (hunk 2 above)
Comment (ghareeb-falazi) [reply src/main/java/org/iac2/common/utility/Edmm.java:277]: I am not sure if `instanceof` is possible in this case... I can only get the type of the attribute and its name but not its value since this describes the attributes of a class not a specific object.

File: src/main/java/org/iac2/service/checking/plugin/implementation/subgraphmatching/comparison/ComponentComparisonResult.java (hunk 3 above)
Comment (ghareeb-falazi) [reply src/main/java/org/iac2/service/checking/plugin/implementation/subgraphmatching/comparison/ComponentComparisonResult.java:3]: I didn't know about them either didn't know about them either, but IntelliJ was really persistent about converting certain classes to records... so I agreed :D
